-- Generated by drizzle-kit (M1-T7, D-21; spec 02 §3 `articles`, spec 03 §8.1 step 1): the MIME type
-- of an audio/video enclosure whose URL is the article's link itself, recorded at ingestion so that
-- extraction skips that link without a request (`skip_media`). Null for every other link; existing
-- rows start null, as their feeds' enclosures were not kept.
ALTER TABLE "articles" ADD COLUMN "link_enclosure_type" text;