import {
  AddExampleBodySchema,
  AdminCreateInvitesBodySchema,
  AdminCreateInvitesResultSchema,
  AdminFeedPageSchema,
  AdminFeedPatchSchema,
  AdminFeedResultSchema,
  AdminFeedsQuerySchema,
  AdminIdParamsSchema,
  AdminInvitePageSchema,
  AdminInvitesQuerySchema,
  AdminLibraryCreateSchema,
  AdminLibraryPageSchema,
  AdminLibraryPatchSchema,
  AdminLibraryQuerySchema,
  AdminLibraryResultSchema,
  AdminOverviewSchema,
  AdminSettingsPatchResultSchema,
  AdminSettingsPatchSchema,
  AdminSettingsSchema,
  AdminUsageQuerySchema,
  AdminUsageSchema,
  AdminUserPageSchema,
  AdminUserParamsSchema,
  AdminUserPatchSchema,
  AdminUserResultSchema,
  AdminUsersQuerySchema,
  AdminWaitlistInviteResultSchema,
  AdminWaitlistPageSchema,
  AdminWaitlistParamsSchema,
  AdminWaitlistQuerySchema,
  AdoptLibraryCardBodySchema,
  AnalysisRequestParamsSchema,
  AnalysisRequestSchema,
  AnalyzeBodySchema,
  AnalyzeResponseSchema,
  ApplyLibraryUpdateBodySchema,
  ArticleCountsQuerySchema,
  ArticleCountsSchema,
  ArticleDetailQuerySchema,
  ArticleDetailSchema,
  ArticleFenceSchema,
  ArticleIdParamsSchema,
  ArticleItemResponseSchema,
  ArticleLabelParamsSchema,
  ArticleListQuerySchema,
  ArticleListResponseSchema,
  BookmarkBodySchema,
  BulkItemsResponseSchema,
  CalibrationResponseSchema,
  CandidateActionBodySchema,
  CardFromArticleBodySchema,
  CardIdParamsSchema,
  CardListSchema,
  CardMutationResponseSchema,
  CardSuggestionListSchema,
  CreateCardBodySchema,
  CreateInviteBodySchema,
  CreateInviteResponseSchema,
  CreateLabelBodySchema,
  CreateRuleBodySchema,
  CreateRuleResponseSchema,
  CredentialListSchema,
  CredentialResultSchema,
  DevLastEmailSchema,
  DwellBodySchema,
  DwellResponseSchema,
  FeedIdParamsSchema,
  FeedMarkReadBodySchema,
  FeedPreferenceBodySchema,
  FeedPreferenceListSchema,
  FeedPreferenceSchema,
  FolderRenameResultSchema,
  FolderRenameSchema,
  InferenceChangeSchema,
  InviteListSchema,
  LabelBodySchema,
  LabelListSchema,
  LabelMutationResponseSchema,
  LibraryCandidatesQuerySchema,
  LibraryCandidatesSchema,
  LibraryPageSchema,
  LibraryQuerySchema,
  LibraryUpdateListSchema,
  LibraryUpdateParamsSchema,
  MarkReadBodySchema,
  MarkReadResponseSchema,
  MeExportSchema,
  MePatchSchema,
  MeSchema,
  MuteStoryBodySchema,
  MuteStoryResponseSchema,
  OpmlImportReportSchema,
  OpsEventBodySchema,
  OpsEventResultSchema,
  PromoteBodySchema,
  PromoteResultSchema,
  PromotionRequestBodySchema,
  PromotionRequestResultSchema,
  PromptAnswerBodySchema,
  ProviderParamsSchema,
  PublicationRequestListSchema,
  PublicationResponseSchema,
  QueuedSchema,
  RateBulkBodySchema,
  RatingBodySchema,
  RatingResponseSchema,
  ReadBodySchema,
  RemoveExampleBodySchema,
  RequestCodeBodySchema,
  RequestCodeResponseSchema,
  ResetBreakerBodySchema,
  ResetBreakerResultSchema,
  RespondPublicationBodySchema,
  RetryCaptureBodySchema,
  RevokeCredentialQuerySchema,
  RuleIdParamsSchema,
  RuleListSchema,
  SessionListSchema,
  SessionParamsSchema,
  StageCredentialBodySchema,
  SubscribeBodySchema,
  SubscribeOkSchema,
  SubscriptionEnvelopeSchema,
  SubscriptionListSchema,
  SubscriptionPatchSchema,
  SuggestionParamsSchema,
  TopicListSchema,
  TranslationsReprocessBodySchema,
  UndoBodySchema,
  UpdateCardBodySchema,
  UpdateLabelBodySchema,
  VerifyBodySchema,
  VerifyResponseSchema,
  WaitlistBodySchema,
  WaitlistResponseSchema,
} from '@bantoozi/shared';
import { z } from 'zod';

import { defineRoute } from './route.js';

// The probe responses are defined inline in apps/api/src/routes/health.ts and are not exported.
const HealthResponseSchema = z.object({ status: z.literal('ok') });
const ReadyCheckSchema = z.enum(['ok', 'pending', 'unreachable']);
const ReadyResponseSchema = z.object({
  status: z.enum(['ready', 'not_ready']),
  checks: z.object({ database: ReadyCheckSchema, migrations: ReadyCheckSchema }),
});

/**
 * Every operation of spec 08, hand-written because the OpenAPI snapshot has neither the required
 * headers nor named schemas. `idempotent` is true for each authenticated mutation (the API wraps it
 * in `request.mutate`); the sign-in flow, the waitlist and the bearer-token ops event are exempt.
 * apps/web/test/api/routes.test.ts compares the method and path of each entry with
 * apps/api/test/expected-operations.txt.
 */
export const routes = {
  // ── Sign-in, sessions, invites, waitlist (spec 08 §2) ──────────────────────────────────────────
  authRequestCode: defineRoute({
    method: 'POST',
    path: '/auth/request-code',
    auth: 'public',
    idempotent: false,
    body: RequestCodeBodySchema,
    response: RequestCodeResponseSchema,
  }),
  authVerify: defineRoute({
    method: 'POST',
    path: '/auth/verify',
    auth: 'public',
    idempotent: false,
    body: VerifyBodySchema,
    response: VerifyResponseSchema,
  }),
  authLogout: defineRoute({
    method: 'POST',
    path: '/auth/logout',
    auth: 'user',
    idempotent: false,
    response: null,
  }),
  authSessionList: defineRoute({
    method: 'GET',
    path: '/auth/sessions',
    auth: 'user',
    idempotent: false,
    response: SessionListSchema,
  }),
  authSessionRevoke: defineRoute({
    method: 'DELETE',
    path: '/auth/sessions/:id',
    auth: 'user',
    idempotent: true,
    params: SessionParamsSchema,
    response: null,
  }),
  inviteList: defineRoute({
    method: 'GET',
    path: '/invites',
    auth: 'user',
    idempotent: false,
    response: InviteListSchema,
  }),
  inviteCreate: defineRoute({
    method: 'POST',
    path: '/invites',
    auth: 'user',
    idempotent: true,
    body: CreateInviteBodySchema,
    response: CreateInviteResponseSchema,
  }),
  waitlistJoin: defineRoute({
    method: 'POST',
    path: '/waitlist',
    auth: 'public',
    idempotent: false,
    body: WaitlistBodySchema,
    response: WaitlistResponseSchema,
  }),

  // ── Me, preferences, export, delete (spec 08 §3) ───────────────────────────────────────────────
  meGet: defineRoute({
    method: 'GET',
    path: '/me',
    auth: 'user',
    idempotent: false,
    response: MeSchema,
  }),
  meUpdate: defineRoute({
    method: 'PATCH',
    path: '/me',
    auth: 'user',
    idempotent: true,
    body: MePatchSchema,
    response: MeSchema,
  }),
  meDelete: defineRoute({
    method: 'DELETE',
    path: '/me',
    auth: 'user',
    idempotent: true,
    response: null,
  }),
  meExport: defineRoute({
    method: 'GET',
    path: '/me/export',
    auth: 'user',
    idempotent: false,
    response: MeExportSchema,
  }),

  // ── Subscriptions, feed preferences, analysis requests (spec 08 §4) ────────────────────────────
  subscriptionsList: defineRoute({
    method: 'GET',
    path: '/subscriptions',
    auth: 'user',
    idempotent: false,
    response: SubscriptionListSchema,
  }),
  subscriptionsCreate: defineRoute({
    method: 'POST',
    path: '/subscriptions',
    auth: 'user',
    idempotent: true,
    body: SubscribeBodySchema,
    response: SubscribeOkSchema,
  }),
  subscriptionsUpdate: defineRoute({
    method: 'PATCH',
    path: '/subscriptions/:feedId',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    body: SubscriptionPatchSchema,
    response: SubscriptionEnvelopeSchema,
  }),
  subscriptionsDelete: defineRoute({
    method: 'DELETE',
    path: '/subscriptions/:feedId',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    response: null,
  }),
  subscriptionsSetInference: defineRoute({
    method: 'POST',
    path: '/subscriptions/:feedId/inference',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    body: InferenceChangeSchema,
    response: SubscriptionEnvelopeSchema,
  }),
  subscriptionsAnalyze: defineRoute({
    method: 'POST',
    path: '/subscriptions/:feedId/analyze',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    body: AnalyzeBodySchema,
    response: AnalyzeResponseSchema,
  }),
  subscriptionsMarkRead: defineRoute({
    method: 'POST',
    path: '/subscriptions/:feedId/mark-read',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    body: FeedMarkReadBodySchema,
    response: MarkReadResponseSchema,
  }),
  subscriptionsImportOpml: defineRoute({
    method: 'POST',
    path: '/subscriptions/import-opml',
    auth: 'user',
    idempotent: true,
    body: 'multipart',
    response: OpmlImportReportSchema,
  }),
  subscriptionsExportOpml: defineRoute({
    method: 'GET',
    path: '/subscriptions/export-opml',
    auth: 'user',
    idempotent: false,
    response: 'text',
  }),
  subscriptionsRenameFolder: defineRoute({
    method: 'POST',
    path: '/subscriptions/folders/rename',
    auth: 'user',
    idempotent: true,
    body: FolderRenameSchema,
    response: FolderRenameResultSchema,
  }),
  analysisRequestGet: defineRoute({
    method: 'GET',
    path: '/analysis-requests/:id',
    auth: 'user',
    idempotent: false,
    params: AnalysisRequestParamsSchema,
    response: AnalysisRequestSchema,
  }),
  feedPreferenceList: defineRoute({
    method: 'GET',
    path: '/feed-preferences',
    auth: 'user',
    idempotent: false,
    response: FeedPreferenceListSchema,
  }),
  feedPreferenceSet: defineRoute({
    method: 'PUT',
    path: '/feed-preferences/:feedId',
    auth: 'user',
    idempotent: true,
    params: FeedIdParamsSchema,
    body: FeedPreferenceBodySchema,
    response: FeedPreferenceSchema,
  }),

  // ── Reader: list, counts, detail (spec 08 §5.1) ────────────────────────────────────────────────
  articleList: defineRoute({
    method: 'GET',
    path: '/articles',
    auth: 'user',
    idempotent: false,
    query: ArticleListQuerySchema,
    response: ArticleListResponseSchema,
  }),
  articleCounts: defineRoute({
    method: 'GET',
    path: '/articles/counts',
    auth: 'user',
    idempotent: false,
    query: ArticleCountsQuerySchema,
    response: ArticleCountsSchema,
  }),
  articleCalibration: defineRoute({
    method: 'GET',
    path: '/articles/calibration',
    auth: 'user',
    idempotent: false,
    response: CalibrationResponseSchema,
  }),
  articleGet: defineRoute({
    method: 'GET',
    path: '/articles/:id',
    auth: 'user',
    idempotent: false,
    params: ArticleIdParamsSchema,
    query: ArticleDetailQuerySchema,
    response: ArticleDetailSchema,
  }),

  // ── Reader actions (spec 08 §5.3, §5.4) ────────────────────────────────────────────────────────
  articleRead: defineRoute({
    method: 'POST',
    path: '/articles/:id/read',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: ReadBodySchema,
    response: ArticleItemResponseSchema,
  }),
  articleUnread: defineRoute({
    method: 'POST',
    path: '/articles/:id/unread',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: ArticleFenceSchema,
    response: ArticleItemResponseSchema,
  }),
  articleUnhide: defineRoute({
    method: 'POST',
    path: '/articles/:id/unhide',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: ArticleFenceSchema,
    response: ArticleItemResponseSchema,
  }),
  articleOpen: defineRoute({
    method: 'POST',
    path: '/articles/:id/open',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: ArticleFenceSchema,
    response: ArticleItemResponseSchema,
  }),
  articleDwell: defineRoute({
    method: 'POST',
    path: '/articles/:id/dwell',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: DwellBodySchema,
    response: DwellResponseSchema,
  }),
  articleRate: defineRoute({
    method: 'POST',
    path: '/articles/:id/rating',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: RatingBodySchema,
    response: RatingResponseSchema,
  }),
  articlePromptAnswer: defineRoute({
    method: 'POST',
    path: '/articles/:id/prompt-answer',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: PromptAnswerBodySchema,
    response: ArticleItemResponseSchema,
  }),
  articleBookmark: defineRoute({
    method: 'POST',
    path: '/articles/:id/bookmark',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: BookmarkBodySchema,
    response: ArticleItemResponseSchema,
  }),
  // The one DELETE with a fence: it travels in the query string, never in a body.
  articleUnbookmark: defineRoute({
    method: 'DELETE',
    path: '/articles/:id/bookmark',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    query: ArticleFenceSchema,
    response: ArticleItemResponseSchema,
  }),
  articleRetryCapture: defineRoute({
    method: 'POST',
    path: '/articles/:id/bookmark/retry-capture',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: RetryCaptureBodySchema,
    response: ArticleItemResponseSchema,
  }),
  articleLabelAdd: defineRoute({
    method: 'POST',
    path: '/articles/:id/labels',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: LabelBodySchema,
    response: ArticleItemResponseSchema,
  }),
  articleLabelRemove: defineRoute({
    method: 'DELETE',
    path: '/articles/:id/labels/:labelId',
    auth: 'user',
    idempotent: true,
    params: ArticleLabelParamsSchema,
    query: ArticleFenceSchema,
    response: ArticleItemResponseSchema,
  }),
  articleMuteStory: defineRoute({
    method: 'POST',
    path: '/articles/:id/mute-story',
    auth: 'user',
    idempotent: true,
    params: ArticleIdParamsSchema,
    body: MuteStoryBodySchema,
    response: MuteStoryResponseSchema,
  }),
  articleMarkRead: defineRoute({
    method: 'POST',
    path: '/articles/mark-read',
    auth: 'user',
    idempotent: true,
    body: MarkReadBodySchema,
    response: MarkReadResponseSchema,
  }),
  articleRateBulk: defineRoute({
    method: 'POST',
    path: '/articles/rate-bulk',
    auth: 'user',
    idempotent: true,
    body: RateBulkBodySchema,
    response: BulkItemsResponseSchema,
  }),
  articleUndo: defineRoute({
    method: 'POST',
    path: '/articles/undo',
    auth: 'user',
    idempotent: true,
    body: UndoBodySchema,
    response: BulkItemsResponseSchema,
  }),

  // ── Cards, suggestions, publication requests (spec 08 §7) ──────────────────────────────────────
  cardList: defineRoute({
    method: 'GET',
    path: '/cards',
    auth: 'user',
    idempotent: false,
    response: CardListSchema,
  }),
  cardCreate: defineRoute({
    method: 'POST',
    path: '/cards',
    auth: 'user',
    idempotent: true,
    body: CreateCardBodySchema,
    response: CardMutationResponseSchema,
  }),
  cardFromArticle: defineRoute({
    method: 'POST',
    path: '/cards/from-article',
    auth: 'user',
    idempotent: true,
    body: CardFromArticleBodySchema,
    response: CardMutationResponseSchema,
  }),
  cardUpdate: defineRoute({
    method: 'PATCH',
    path: '/cards/:id',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: UpdateCardBodySchema,
    response: CardMutationResponseSchema,
  }),
  cardDelete: defineRoute({
    method: 'DELETE',
    path: '/cards/:id',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    response: null,
  }),
  cardExampleAdd: defineRoute({
    method: 'POST',
    path: '/cards/:id/examples',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: AddExampleBodySchema,
    response: CardMutationResponseSchema,
  }),
  cardExampleRemove: defineRoute({
    method: 'POST',
    path: '/cards/:id/examples/remove',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: RemoveExampleBodySchema,
    response: CardMutationResponseSchema,
  }),
  cardSuggestionList: defineRoute({
    method: 'GET',
    path: '/cards/suggestions',
    auth: 'user',
    idempotent: false,
    response: CardSuggestionListSchema,
  }),
  cardSuggestionDismiss: defineRoute({
    method: 'POST',
    path: '/cards/suggestions/:cardId/dismiss',
    auth: 'user',
    idempotent: true,
    params: SuggestionParamsSchema,
    response: null,
  }),
  cardPublicationRequestList: defineRoute({
    method: 'GET',
    path: '/cards/publication-requests',
    auth: 'user',
    idempotent: false,
    response: PublicationRequestListSchema,
  }),
  cardPublicationRespond: defineRoute({
    method: 'POST',
    path: '/cards/publication-requests/:id/respond',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: RespondPublicationBodySchema,
    response: PublicationResponseSchema,
  }),

  // ── Labels (spec 08 §7) ────────────────────────────────────────────────────────────────────────
  labelList: defineRoute({
    method: 'GET',
    path: '/labels',
    auth: 'user',
    idempotent: false,
    response: LabelListSchema,
  }),
  labelCreate: defineRoute({
    method: 'POST',
    path: '/labels',
    auth: 'user',
    idempotent: true,
    body: CreateLabelBodySchema,
    response: LabelMutationResponseSchema,
  }),
  labelUpdate: defineRoute({
    method: 'PATCH',
    path: '/labels/:id',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: UpdateLabelBodySchema,
    response: LabelMutationResponseSchema,
  }),
  labelDelete: defineRoute({
    method: 'DELETE',
    path: '/labels/:id',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    response: null,
  }),
  labelExampleAdd: defineRoute({
    method: 'POST',
    path: '/labels/:id/examples',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: AddExampleBodySchema,
    response: LabelMutationResponseSchema,
  }),
  labelExampleRemove: defineRoute({
    method: 'POST',
    path: '/labels/:id/examples/remove',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: RemoveExampleBodySchema,
    response: LabelMutationResponseSchema,
  }),

  // ── Library and topics (spec 08 §7) ────────────────────────────────────────────────────────────
  libraryList: defineRoute({
    method: 'GET',
    path: '/library',
    auth: 'user',
    idempotent: false,
    query: LibraryQuerySchema,
    response: LibraryPageSchema,
  }),
  libraryAdopt: defineRoute({
    method: 'POST',
    path: '/library/:id/adopt',
    auth: 'user',
    idempotent: true,
    params: CardIdParamsSchema,
    body: AdoptLibraryCardBodySchema,
    response: CardMutationResponseSchema,
  }),
  libraryUpdateList: defineRoute({
    method: 'GET',
    path: '/library/updates',
    auth: 'user',
    idempotent: false,
    response: LibraryUpdateListSchema,
  }),
  libraryUpdateApply: defineRoute({
    method: 'POST',
    path: '/library/:id/updates/:newId/apply',
    auth: 'user',
    idempotent: true,
    params: LibraryUpdateParamsSchema,
    body: ApplyLibraryUpdateBodySchema,
    response: CardMutationResponseSchema,
  }),
  topicList: defineRoute({
    method: 'GET',
    path: '/topics',
    auth: 'user',
    idempotent: false,
    response: TopicListSchema,
  }),

  // ── Rules (spec 08 §8) ─────────────────────────────────────────────────────────────────────────
  ruleList: defineRoute({
    method: 'GET',
    path: '/rules',
    auth: 'user',
    idempotent: false,
    response: RuleListSchema,
  }),
  ruleCreate: defineRoute({
    method: 'POST',
    path: '/rules',
    auth: 'user',
    idempotent: true,
    body: CreateRuleBodySchema,
    response: CreateRuleResponseSchema,
  }),
  ruleDelete: defineRoute({
    method: 'DELETE',
    path: '/rules/:id',
    auth: 'user',
    idempotent: true,
    params: RuleIdParamsSchema,
    response: null,
  }),

  // ── Admin (spec 08 §9) ─────────────────────────────────────────────────────────────────────────
  adminOverview: defineRoute({
    method: 'GET',
    path: '/admin/overview',
    auth: 'admin',
    idempotent: false,
    response: AdminOverviewSchema,
  }),
  adminUsage: defineRoute({
    method: 'GET',
    path: '/admin/usage',
    auth: 'admin',
    idempotent: false,
    query: AdminUsageQuerySchema,
    response: AdminUsageSchema,
  }),
  adminEngineResetBreaker: defineRoute({
    method: 'POST',
    path: '/admin/engine/reset-breaker',
    auth: 'admin',
    idempotent: true,
    body: ResetBreakerBodySchema,
    response: ResetBreakerResultSchema,
  }),
  adminTranslationsReprocess: defineRoute({
    method: 'POST',
    path: '/admin/translations/reprocess',
    auth: 'admin',
    idempotent: true,
    body: TranslationsReprocessBodySchema,
    response: QueuedSchema,
  }),
  adminSettingsGet: defineRoute({
    method: 'GET',
    path: '/admin/settings',
    auth: 'admin',
    idempotent: false,
    response: AdminSettingsSchema,
  }),
  adminSettingsUpdate: defineRoute({
    method: 'PATCH',
    path: '/admin/settings',
    auth: 'admin',
    idempotent: true,
    body: AdminSettingsPatchSchema,
    response: AdminSettingsPatchResultSchema,
  }),
  adminCredentialList: defineRoute({
    method: 'GET',
    path: '/admin/engine/credentials',
    auth: 'admin',
    idempotent: false,
    response: CredentialListSchema,
  }),
  adminCredentialStage: defineRoute({
    method: 'PUT',
    path: '/admin/engine/credentials/:provider',
    auth: 'admin',
    idempotent: true,
    params: ProviderParamsSchema,
    body: StageCredentialBodySchema,
    response: CredentialResultSchema,
  }),
  adminCredentialValidate: defineRoute({
    method: 'POST',
    path: '/admin/engine/credentials/:provider/validate',
    auth: 'admin',
    idempotent: true,
    params: ProviderParamsSchema,
    body: CandidateActionBodySchema,
    response: CredentialResultSchema,
  }),
  adminCredentialActivate: defineRoute({
    method: 'POST',
    path: '/admin/engine/credentials/:provider/activate',
    auth: 'admin',
    idempotent: true,
    params: ProviderParamsSchema,
    body: CandidateActionBodySchema,
    response: CredentialResultSchema,
  }),
  adminCredentialRevoke: defineRoute({
    method: 'DELETE',
    path: '/admin/engine/credentials/:provider',
    auth: 'admin',
    idempotent: true,
    params: ProviderParamsSchema,
    query: RevokeCredentialQuerySchema,
    response: CredentialResultSchema,
  }),
  adminFeedList: defineRoute({
    method: 'GET',
    path: '/admin/feeds',
    auth: 'admin',
    idempotent: false,
    query: AdminFeedsQuerySchema,
    response: AdminFeedPageSchema,
  }),
  adminFeedUpdate: defineRoute({
    method: 'PATCH',
    path: '/admin/feeds/:id',
    auth: 'admin',
    idempotent: true,
    params: AdminIdParamsSchema,
    body: AdminFeedPatchSchema,
    response: AdminFeedResultSchema,
  }),
  adminFeedReset: defineRoute({
    method: 'POST',
    path: '/admin/feeds/:id/reset',
    auth: 'admin',
    idempotent: true,
    params: AdminIdParamsSchema,
    response: AdminFeedResultSchema,
  }),
  adminUserList: defineRoute({
    method: 'GET',
    path: '/admin/users',
    auth: 'admin',
    idempotent: false,
    query: AdminUsersQuerySchema,
    response: AdminUserPageSchema,
  }),
  adminUserUpdate: defineRoute({
    method: 'PATCH',
    path: '/admin/users/:id',
    auth: 'admin',
    idempotent: true,
    params: AdminUserParamsSchema,
    body: AdminUserPatchSchema,
    response: AdminUserResultSchema,
  }),
  adminInviteList: defineRoute({
    method: 'GET',
    path: '/admin/invites',
    auth: 'admin',
    idempotent: false,
    query: AdminInvitesQuerySchema,
    response: AdminInvitePageSchema,
  }),
  adminInviteCreate: defineRoute({
    method: 'POST',
    path: '/admin/invites',
    auth: 'admin',
    idempotent: true,
    body: AdminCreateInvitesBodySchema,
    response: AdminCreateInvitesResultSchema,
  }),
  adminWaitlistList: defineRoute({
    method: 'GET',
    path: '/admin/waitlist',
    auth: 'admin',
    idempotent: false,
    query: AdminWaitlistQuerySchema,
    response: AdminWaitlistPageSchema,
  }),
  adminWaitlistInvite: defineRoute({
    method: 'POST',
    path: '/admin/waitlist/:id/invite',
    auth: 'admin',
    idempotent: true,
    params: AdminWaitlistParamsSchema,
    response: AdminWaitlistInviteResultSchema,
  }),
  adminLibraryList: defineRoute({
    method: 'GET',
    path: '/admin/library',
    auth: 'admin',
    idempotent: false,
    query: AdminLibraryQuerySchema,
    response: AdminLibraryPageSchema,
  }),
  adminLibraryCandidates: defineRoute({
    method: 'GET',
    path: '/admin/library/candidates',
    auth: 'admin',
    idempotent: false,
    query: LibraryCandidatesQuerySchema,
    response: LibraryCandidatesSchema,
  }),
  adminLibraryCreate: defineRoute({
    method: 'POST',
    path: '/admin/library',
    auth: 'admin',
    idempotent: true,
    body: AdminLibraryCreateSchema,
    response: AdminLibraryResultSchema,
  }),
  adminLibraryUpdate: defineRoute({
    method: 'PATCH',
    path: '/admin/library/:id',
    auth: 'admin',
    idempotent: true,
    params: AdminIdParamsSchema,
    body: AdminLibraryPatchSchema,
    response: AdminLibraryResultSchema,
  }),
  adminLibraryPromotionRequest: defineRoute({
    method: 'POST',
    path: '/admin/library/promotion-requests',
    auth: 'admin',
    idempotent: true,
    body: PromotionRequestBodySchema,
    response: PromotionRequestResultSchema,
  }),
  adminLibraryPromote: defineRoute({
    method: 'POST',
    path: '/admin/library/promote',
    auth: 'admin',
    idempotent: true,
    body: PromoteBodySchema,
    response: PromoteResultSchema,
  }),

  // ── Host and test routes (spec 08 §10): no browser flow uses them ──────────────────────────────
  // The METRICS_TOKEN bearer authenticates this one, not the session cookie.
  adminOpsEvent: defineRoute({
    method: 'POST',
    path: '/admin/ops-event',
    auth: 'public',
    idempotent: false,
    body: OpsEventBodySchema,
    response: OpsEventResultSchema,
  }),
  // An admin session or the METRICS_TOKEN bearer; Prometheus text.
  metrics: defineRoute({
    method: 'GET',
    path: '/metrics',
    auth: 'admin',
    idempotent: false,
    response: 'text',
  }),
  healthz: defineRoute({
    method: 'GET',
    path: '/healthz',
    auth: 'public',
    idempotent: false,
    response: HealthResponseSchema,
  }),
  readyz: defineRoute({
    method: 'GET',
    path: '/readyz',
    auth: 'public',
    idempotent: false,
    response: ReadyResponseSchema,
  }),
  // Registered only when the API runs with NODE_ENV=test; E2E reads the sign-in code from it.
  devLastEmail: defineRoute({
    method: 'GET',
    path: '/dev/last-email',
    auth: 'public',
    idempotent: false,
    response: DevLastEmailSchema,
  }),
} as const;
